version: '3'

services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    expose:
      - "5000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
      - appid=143
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    links:
      - app